// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="backsub,hls_ip_2014_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.465000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1995,HLS_SYN_DSP=18,HLS_SYN_FF=7119,HLS_SYN_LUT=14009}" *)

module backsub (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_array_address0,
        data_array_ce0,
        data_array_q0,
        out_frame_address0,
        out_frame_ce0,
        out_frame_we0,
        out_frame_d0,
        init,
        ap_return
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 15'b1;
parameter    ap_ST_st2_fsm_1 = 15'b10;
parameter    ap_ST_st3_fsm_2 = 15'b100;
parameter    ap_ST_st4_fsm_3 = 15'b1000;
parameter    ap_ST_st5_fsm_4 = 15'b10000;
parameter    ap_ST_st6_fsm_5 = 15'b100000;
parameter    ap_ST_st7_fsm_6 = 15'b1000000;
parameter    ap_ST_st8_fsm_7 = 15'b10000000;
parameter    ap_ST_st9_fsm_8 = 15'b100000000;
parameter    ap_ST_st10_fsm_9 = 15'b1000000000;
parameter    ap_ST_st11_fsm_10 = 15'b10000000000;
parameter    ap_ST_st12_fsm_11 = 15'b100000000000;
parameter    ap_ST_st13_fsm_12 = 15'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 15'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 15'b100000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv17_0 = 17'b00000000000000000;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_42000000 = 32'b1000010000000000000000000000000;
parameter    ap_const_lv32_43340000 = 32'b1000011001101000000000000000000;
parameter    ap_const_lv32_42F00000 = 32'b1000010111100000000000000000000;
parameter    ap_const_lv32_435C0000 = 32'b1000011010111000000000000000000;
parameter    ap_const_lv32_43C80000 = 32'b1000011110010000000000000000000;
parameter    ap_const_lv32_3D4CCCCD = 32'b111101010011001100110011001101;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv8_F0 = 8'b11110000;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv8_A0 = 8'b10100000;
parameter    ap_const_lv17_1 = 17'b1;
parameter    ap_const_lv17_12C00 = 17'b10010110000000000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv19_1 = 19'b1;
parameter    ap_const_lv13_0 = 13'b0000000000000;
parameter    ap_const_lv19_2 = 19'b10;
parameter    ap_const_lv19_3 = 19'b11;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] data_array_address0;
output   data_array_ce0;
input  [31:0] data_array_q0;
output  [16:0] out_frame_address0;
output   out_frame_ce0;
output   out_frame_we0;
output  [7:0] out_frame_d0;
input   init;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] data_array_address0;
reg data_array_ce0;
reg[16:0] out_frame_address0;
reg out_frame_ce0;
reg out_frame_we0;
(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm = 15'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_31;
reg   [18:0] mean_address0;
reg    mean_ce0;
reg    mean_we0;
reg   [31:0] mean_d0;
wire   [31:0] mean_q0;
reg   [18:0] mean_address1;
reg    mean_ce1;
reg    mean_we1;
reg   [31:0] mean_d1;
reg   [18:0] sigma_address0;
reg    sigma_ce0;
reg    sigma_we0;
reg   [31:0] sigma_d0;
wire   [31:0] sigma_q0;
reg   [18:0] sigma_address1;
reg    sigma_ce1;
reg    sigma_we1;
wire   [31:0] sigma_d1;
reg   [18:0] weight_address0;
reg    weight_ce0;
reg    weight_we0;
reg   [31:0] weight_d0;
wire   [31:0] weight_q0;
reg   [18:0] weight_address1;
reg    weight_ce1;
reg    weight_we1;
wire   [31:0] weight_d1;
reg   [18:0] matchsum_address0;
reg    matchsum_ce0;
reg    matchsum_we0;
reg   [7:0] matchsum_d0;
wire   [7:0] matchsum_q0;
reg   [18:0] matchsum_address1;
reg    matchsum_ce1;
reg    matchsum_we1;
wire   [7:0] matchsum_d1;
reg   [18:0] back_gauss_address0;
reg    back_gauss_ce0;
reg    back_gauss_we0;
reg   [0:0] back_gauss_d0;
wire   [0:0] back_gauss_q0;
reg   [18:0] back_gauss_address1;
reg    back_gauss_ce1;
reg    back_gauss_we1;
reg   [0:0] back_gauss_d1;
reg   [7:0] reg_478;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_128;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_135;
wire   [0:0] init_read_read_fu_110_p2;
wire   [0:0] exitcond1_fu_483_p2;
reg   [0:0] exitcond1_reg_793;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_150;
wire   [7:0] idxRow_1_fu_489_p2;
reg   [7:0] idxRow_1_reg_797;
reg   [15:0] p_lshr_f1_cast_reg_802;
wire   [7:0] idxCols_1_fu_545_p2;
reg   [7:0] idxCols_1_reg_810;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_166;
wire   [15:0] i_2_fu_551_p2;
reg   [15:0] i_2_reg_815;
wire   [0:0] exitcond_fu_539_p2;
wire   [7:0] pix_y1_fu_561_p1;
reg   [7:0] pix_y1_reg_825;
wire   [16:0] tmp_8_fu_566_p3;
reg   [16:0] tmp_8_reg_830;
wire   [16:0] tmp_12_fu_578_p2;
reg   [16:0] tmp_12_reg_837;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_186;
wire   [16:0] i_1_fu_594_p2;
reg   [16:0] i_1_reg_846;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_bdd_195;
wire   [18:0] tmp_fu_600_p3;
reg   [18:0] tmp_reg_851;
wire   [0:0] exitcond4_fu_588_p2;
wire   [7:0] idxRow_2_fu_690_p2;
reg   [7:0] idxRow_2_reg_860;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_209;
reg   [15:0] p_lshr_f_cast_reg_865;
wire   [0:0] exitcond3_fu_684_p2;
wire   [7:0] idxCols_2_fu_746_p2;
reg   [7:0] idxCols_2_reg_873;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_227;
wire   [15:0] i_3_fu_752_p2;
reg   [15:0] i_3_reg_878;
wire   [0:0] exitcond2_fu_740_p2;
wire   [7:0] pix_y1_1_fu_762_p1;
reg   [7:0] pix_y1_1_reg_888;
wire   [16:0] tmp_5_fu_767_p3;
reg   [16:0] tmp_5_reg_893;
wire   [16:0] tmp_14_fu_779_p2;
reg   [16:0] tmp_14_reg_900;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_bdd_247;
wire    grp_backsub_EM_ALGO_fu_435_ap_start;
wire    grp_backsub_EM_ALGO_fu_435_ap_done;
wire    grp_backsub_EM_ALGO_fu_435_ap_idle;
wire    grp_backsub_EM_ALGO_fu_435_ap_ready;
reg   [7:0] grp_backsub_EM_ALGO_fu_435_pixel;
reg   [16:0] grp_backsub_EM_ALGO_fu_435_pos_r;
wire   [18:0] grp_backsub_EM_ALGO_fu_435_mean_address0;
wire    grp_backsub_EM_ALGO_fu_435_mean_ce0;
wire    grp_backsub_EM_ALGO_fu_435_mean_we0;
wire   [31:0] grp_backsub_EM_ALGO_fu_435_mean_d0;
wire   [31:0] grp_backsub_EM_ALGO_fu_435_mean_q0;
wire   [18:0] grp_backsub_EM_ALGO_fu_435_sigma_address0;
wire    grp_backsub_EM_ALGO_fu_435_sigma_ce0;
wire    grp_backsub_EM_ALGO_fu_435_sigma_we0;
wire   [31:0] grp_backsub_EM_ALGO_fu_435_sigma_d0;
wire   [31:0] grp_backsub_EM_ALGO_fu_435_sigma_q0;
wire   [18:0] grp_backsub_EM_ALGO_fu_435_weight_address0;
wire    grp_backsub_EM_ALGO_fu_435_weight_ce0;
wire    grp_backsub_EM_ALGO_fu_435_weight_we0;
wire   [31:0] grp_backsub_EM_ALGO_fu_435_weight_d0;
wire   [31:0] grp_backsub_EM_ALGO_fu_435_weight_q0;
wire   [18:0] grp_backsub_EM_ALGO_fu_435_matchsum_address0;
wire    grp_backsub_EM_ALGO_fu_435_matchsum_ce0;
wire    grp_backsub_EM_ALGO_fu_435_matchsum_we0;
wire   [7:0] grp_backsub_EM_ALGO_fu_435_matchsum_d0;
wire   [7:0] grp_backsub_EM_ALGO_fu_435_matchsum_q0;
wire   [18:0] grp_backsub_EM_ALGO_fu_435_back_gauss_address0;
wire    grp_backsub_EM_ALGO_fu_435_back_gauss_ce0;
wire    grp_backsub_EM_ALGO_fu_435_back_gauss_we0;
wire   [0:0] grp_backsub_EM_ALGO_fu_435_back_gauss_d0;
wire   [0:0] grp_backsub_EM_ALGO_fu_435_back_gauss_q0;
wire   [18:0] grp_backsub_EM_ALGO_fu_435_back_gauss_address1;
wire    grp_backsub_EM_ALGO_fu_435_back_gauss_ce1;
wire    grp_backsub_EM_ALGO_fu_435_back_gauss_we1;
wire   [0:0] grp_backsub_EM_ALGO_fu_435_back_gauss_d1;
wire   [0:0] grp_backsub_EM_ALGO_fu_435_ap_return;
reg   [7:0] idxRow2_reg_379;
reg   [7:0] idxCols3_reg_390;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_300;
reg   [16:0] i_reg_401;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_bdd_312;
reg   [7:0] idxRow_reg_412;
reg   [7:0] idxCols_reg_423;
reg    ap_sig_cseq_ST_st15_fsm_14;
reg    ap_sig_bdd_329;
reg    grp_backsub_EM_ALGO_fu_435_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_342;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_349;
wire   [63:0] tmp_7_fu_556_p1;
wire   [63:0] tmp_s_fu_574_p1;
wire   [63:0] tmp_16_fu_584_p1;
wire   [63:0] tmp_1_fu_608_p1;
wire   [63:0] tmp_17_fu_631_p1;
wire   [63:0] tmp_20_fu_653_p1;
wire   [63:0] tmp_22_fu_675_p1;
wire   [63:0] tmp_6_fu_757_p1;
wire   [63:0] tmp_10_fu_775_p1;
wire   [63:0] tmp_18_fu_785_p1;
wire   [15:0] p_shl1_fu_495_p3;
wire   [13:0] p_shl2_fu_507_p3;
wire   [16:0] p_shl1_cast_fu_503_p1;
wire   [16:0] p_shl2_cast_fu_515_p1;
wire   [16:0] tmp_2_fu_519_p2;
wire   [15:0] idxCols3_cast2_fu_535_p1;
wire   [18:0] tmp_11_fu_617_p2;
wire   [31:0] mean_addr1_fu_623_p3;
wire   [18:0] tmp_19_fu_640_p2;
wire   [31:0] mean_addr2_fu_645_p3;
wire   [18:0] tmp_21_fu_662_p2;
wire   [31:0] mean_addr3_fu_667_p3;
wire   [15:0] p_shl_fu_696_p3;
wire   [13:0] p_shl3_fu_708_p3;
wire   [16:0] p_shl_cast_fu_704_p1;
wire   [16:0] p_shl3_cast_fu_716_p1;
wire   [16:0] tmp_4_fu_720_p2;
wire   [15:0] idxCols_cast6_fu_736_p1;
reg   [14:0] ap_NS_fsm;


backsub_mean #(
    .DataWidth( 32 ),
    .AddressRange( 307200 ),
    .AddressWidth( 19 ))
mean_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( mean_address0 ),
    .ce0( mean_ce0 ),
    .we0( mean_we0 ),
    .d0( mean_d0 ),
    .q0( mean_q0 ),
    .address1( mean_address1 ),
    .ce1( mean_ce1 ),
    .we1( mean_we1 ),
    .d1( mean_d1 )
);

backsub_mean #(
    .DataWidth( 32 ),
    .AddressRange( 307200 ),
    .AddressWidth( 19 ))
sigma_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( sigma_address0 ),
    .ce0( sigma_ce0 ),
    .we0( sigma_we0 ),
    .d0( sigma_d0 ),
    .q0( sigma_q0 ),
    .address1( sigma_address1 ),
    .ce1( sigma_ce1 ),
    .we1( sigma_we1 ),
    .d1( sigma_d1 )
);

backsub_mean #(
    .DataWidth( 32 ),
    .AddressRange( 307200 ),
    .AddressWidth( 19 ))
weight_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( weight_address0 ),
    .ce0( weight_ce0 ),
    .we0( weight_we0 ),
    .d0( weight_d0 ),
    .q0( weight_q0 ),
    .address1( weight_address1 ),
    .ce1( weight_ce1 ),
    .we1( weight_we1 ),
    .d1( weight_d1 )
);

backsub_matchsum #(
    .DataWidth( 8 ),
    .AddressRange( 307200 ),
    .AddressWidth( 19 ))
matchsum_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( matchsum_address0 ),
    .ce0( matchsum_ce0 ),
    .we0( matchsum_we0 ),
    .d0( matchsum_d0 ),
    .q0( matchsum_q0 ),
    .address1( matchsum_address1 ),
    .ce1( matchsum_ce1 ),
    .we1( matchsum_we1 ),
    .d1( matchsum_d1 )
);

backsub_back_gauss #(
    .DataWidth( 1 ),
    .AddressRange( 307200 ),
    .AddressWidth( 19 ))
back_gauss_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( back_gauss_address0 ),
    .ce0( back_gauss_ce0 ),
    .we0( back_gauss_we0 ),
    .d0( back_gauss_d0 ),
    .q0( back_gauss_q0 ),
    .address1( back_gauss_address1 ),
    .ce1( back_gauss_ce1 ),
    .we1( back_gauss_we1 ),
    .d1( back_gauss_d1 )
);

backsub_EM_ALGO grp_backsub_EM_ALGO_fu_435(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_backsub_EM_ALGO_fu_435_ap_start ),
    .ap_done( grp_backsub_EM_ALGO_fu_435_ap_done ),
    .ap_idle( grp_backsub_EM_ALGO_fu_435_ap_idle ),
    .ap_ready( grp_backsub_EM_ALGO_fu_435_ap_ready ),
    .pixel( grp_backsub_EM_ALGO_fu_435_pixel ),
    .pos_r( grp_backsub_EM_ALGO_fu_435_pos_r ),
    .mean_address0( grp_backsub_EM_ALGO_fu_435_mean_address0 ),
    .mean_ce0( grp_backsub_EM_ALGO_fu_435_mean_ce0 ),
    .mean_we0( grp_backsub_EM_ALGO_fu_435_mean_we0 ),
    .mean_d0( grp_backsub_EM_ALGO_fu_435_mean_d0 ),
    .mean_q0( grp_backsub_EM_ALGO_fu_435_mean_q0 ),
    .sigma_address0( grp_backsub_EM_ALGO_fu_435_sigma_address0 ),
    .sigma_ce0( grp_backsub_EM_ALGO_fu_435_sigma_ce0 ),
    .sigma_we0( grp_backsub_EM_ALGO_fu_435_sigma_we0 ),
    .sigma_d0( grp_backsub_EM_ALGO_fu_435_sigma_d0 ),
    .sigma_q0( grp_backsub_EM_ALGO_fu_435_sigma_q0 ),
    .weight_address0( grp_backsub_EM_ALGO_fu_435_weight_address0 ),
    .weight_ce0( grp_backsub_EM_ALGO_fu_435_weight_ce0 ),
    .weight_we0( grp_backsub_EM_ALGO_fu_435_weight_we0 ),
    .weight_d0( grp_backsub_EM_ALGO_fu_435_weight_d0 ),
    .weight_q0( grp_backsub_EM_ALGO_fu_435_weight_q0 ),
    .matchsum_address0( grp_backsub_EM_ALGO_fu_435_matchsum_address0 ),
    .matchsum_ce0( grp_backsub_EM_ALGO_fu_435_matchsum_ce0 ),
    .matchsum_we0( grp_backsub_EM_ALGO_fu_435_matchsum_we0 ),
    .matchsum_d0( grp_backsub_EM_ALGO_fu_435_matchsum_d0 ),
    .matchsum_q0( grp_backsub_EM_ALGO_fu_435_matchsum_q0 ),
    .back_gauss_address0( grp_backsub_EM_ALGO_fu_435_back_gauss_address0 ),
    .back_gauss_ce0( grp_backsub_EM_ALGO_fu_435_back_gauss_ce0 ),
    .back_gauss_we0( grp_backsub_EM_ALGO_fu_435_back_gauss_we0 ),
    .back_gauss_d0( grp_backsub_EM_ALGO_fu_435_back_gauss_d0 ),
    .back_gauss_q0( grp_backsub_EM_ALGO_fu_435_back_gauss_q0 ),
    .back_gauss_address1( grp_backsub_EM_ALGO_fu_435_back_gauss_address1 ),
    .back_gauss_ce1( grp_backsub_EM_ALGO_fu_435_back_gauss_ce1 ),
    .back_gauss_we1( grp_backsub_EM_ALGO_fu_435_back_gauss_we1 ),
    .back_gauss_d1( grp_backsub_EM_ALGO_fu_435_back_gauss_d1 ),
    .ap_return( grp_backsub_EM_ALGO_fu_435_ap_return )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// grp_backsub_EM_ALGO_fu_435_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_backsub_EM_ALGO_fu_435_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_backsub_EM_ALGO_fu_435_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13))) begin
            grp_backsub_EM_ALGO_fu_435_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_backsub_EM_ALGO_fu_435_ap_ready)) begin
            grp_backsub_EM_ALGO_fu_435_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & ~(init_read_read_fu_110_p2 == ap_const_lv1_0))) begin
        i_reg_401 <= ap_const_lv17_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        i_reg_401 <= i_1_reg_846;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done))) begin
        idxCols3_reg_390 <= idxCols_1_reg_810;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_483_p2 == ap_const_lv1_0))) begin
        idxCols3_reg_390 <= ap_const_lv8_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done) & (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14))) begin
        idxCols_reg_423 <= idxCols_2_reg_873;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & ~(init_read_read_fu_110_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond3_fu_684_p2))) begin
        idxCols_reg_423 <= ap_const_lv8_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == exitcond_fu_539_p2))) begin
        idxRow2_reg_379 <= idxRow_1_reg_797;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (init_read_read_fu_110_p2 == ap_const_lv1_0))) begin
        idxRow2_reg_379 <= ap_const_lv8_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & ~(ap_const_lv1_0 == exitcond2_fu_740_p2))) begin
        idxRow_reg_412 <= idxRow_2_reg_860;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & ~(ap_const_lv1_0 == exitcond4_fu_588_p2))) begin
        idxRow_reg_412 <= ap_const_lv8_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        exitcond1_reg_793 <= exitcond1_fu_483_p2;
        idxRow_1_reg_797 <= idxRow_1_fu_489_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        i_1_reg_846 <= i_1_fu_594_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond_fu_539_p2))) begin
        i_2_reg_815 <= i_2_fu_551_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond2_fu_740_p2))) begin
        i_3_reg_878 <= i_3_fu_752_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        idxCols_1_reg_810 <= idxCols_1_fu_545_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        idxCols_2_reg_873 <= idxCols_2_fu_746_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & ~(init_read_read_fu_110_p2 == ap_const_lv1_0))) begin
        idxRow_2_reg_860 <= idxRow_2_fu_690_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_483_p2 == ap_const_lv1_0))) begin
        p_lshr_f1_cast_reg_802 <= {{tmp_2_fu_519_p2[ap_const_lv32_10 : ap_const_lv32_1]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & ~(init_read_read_fu_110_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond3_fu_684_p2))) begin
        p_lshr_f_cast_reg_865 <= {{tmp_4_fu_720_p2[ap_const_lv32_10 : ap_const_lv32_1]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        pix_y1_1_reg_888 <= pix_y1_1_fu_762_p1;
        tmp_5_reg_893[1] <= tmp_5_fu_767_p3[1];
tmp_5_reg_893[2] <= tmp_5_fu_767_p3[2];
tmp_5_reg_893[3] <= tmp_5_fu_767_p3[3];
tmp_5_reg_893[4] <= tmp_5_fu_767_p3[4];
tmp_5_reg_893[5] <= tmp_5_fu_767_p3[5];
tmp_5_reg_893[6] <= tmp_5_fu_767_p3[6];
tmp_5_reg_893[7] <= tmp_5_fu_767_p3[7];
tmp_5_reg_893[8] <= tmp_5_fu_767_p3[8];
tmp_5_reg_893[9] <= tmp_5_fu_767_p3[9];
tmp_5_reg_893[10] <= tmp_5_fu_767_p3[10];
tmp_5_reg_893[11] <= tmp_5_fu_767_p3[11];
tmp_5_reg_893[12] <= tmp_5_fu_767_p3[12];
tmp_5_reg_893[13] <= tmp_5_fu_767_p3[13];
tmp_5_reg_893[14] <= tmp_5_fu_767_p3[14];
tmp_5_reg_893[15] <= tmp_5_fu_767_p3[15];
tmp_5_reg_893[16] <= tmp_5_fu_767_p3[16];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        pix_y1_reg_825 <= pix_y1_fu_561_p1;
        tmp_8_reg_830[1] <= tmp_8_fu_566_p3[1];
tmp_8_reg_830[2] <= tmp_8_fu_566_p3[2];
tmp_8_reg_830[3] <= tmp_8_fu_566_p3[3];
tmp_8_reg_830[4] <= tmp_8_fu_566_p3[4];
tmp_8_reg_830[5] <= tmp_8_fu_566_p3[5];
tmp_8_reg_830[6] <= tmp_8_fu_566_p3[6];
tmp_8_reg_830[7] <= tmp_8_fu_566_p3[7];
tmp_8_reg_830[8] <= tmp_8_fu_566_p3[8];
tmp_8_reg_830[9] <= tmp_8_fu_566_p3[9];
tmp_8_reg_830[10] <= tmp_8_fu_566_p3[10];
tmp_8_reg_830[11] <= tmp_8_fu_566_p3[11];
tmp_8_reg_830[12] <= tmp_8_fu_566_p3[12];
tmp_8_reg_830[13] <= tmp_8_fu_566_p3[13];
tmp_8_reg_830[14] <= tmp_8_fu_566_p3[14];
tmp_8_reg_830[15] <= tmp_8_fu_566_p3[15];
tmp_8_reg_830[16] <= tmp_8_fu_566_p3[16];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11))) begin
        reg_478 <= {{data_array_q0[ap_const_lv32_17 : ap_const_lv32_10]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        tmp_12_reg_837[1] <= tmp_12_fu_578_p2[1];
tmp_12_reg_837[2] <= tmp_12_fu_578_p2[2];
tmp_12_reg_837[3] <= tmp_12_fu_578_p2[3];
tmp_12_reg_837[4] <= tmp_12_fu_578_p2[4];
tmp_12_reg_837[5] <= tmp_12_fu_578_p2[5];
tmp_12_reg_837[6] <= tmp_12_fu_578_p2[6];
tmp_12_reg_837[7] <= tmp_12_fu_578_p2[7];
tmp_12_reg_837[8] <= tmp_12_fu_578_p2[8];
tmp_12_reg_837[9] <= tmp_12_fu_578_p2[9];
tmp_12_reg_837[10] <= tmp_12_fu_578_p2[10];
tmp_12_reg_837[11] <= tmp_12_fu_578_p2[11];
tmp_12_reg_837[12] <= tmp_12_fu_578_p2[12];
tmp_12_reg_837[13] <= tmp_12_fu_578_p2[13];
tmp_12_reg_837[14] <= tmp_12_fu_578_p2[14];
tmp_12_reg_837[15] <= tmp_12_fu_578_p2[15];
tmp_12_reg_837[16] <= tmp_12_fu_578_p2[16];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        tmp_14_reg_900[1] <= tmp_14_fu_779_p2[1];
tmp_14_reg_900[2] <= tmp_14_fu_779_p2[2];
tmp_14_reg_900[3] <= tmp_14_fu_779_p2[3];
tmp_14_reg_900[4] <= tmp_14_fu_779_p2[4];
tmp_14_reg_900[5] <= tmp_14_fu_779_p2[5];
tmp_14_reg_900[6] <= tmp_14_fu_779_p2[6];
tmp_14_reg_900[7] <= tmp_14_fu_779_p2[7];
tmp_14_reg_900[8] <= tmp_14_fu_779_p2[8];
tmp_14_reg_900[9] <= tmp_14_fu_779_p2[9];
tmp_14_reg_900[10] <= tmp_14_fu_779_p2[10];
tmp_14_reg_900[11] <= tmp_14_fu_779_p2[11];
tmp_14_reg_900[12] <= tmp_14_fu_779_p2[12];
tmp_14_reg_900[13] <= tmp_14_fu_779_p2[13];
tmp_14_reg_900[14] <= tmp_14_fu_779_p2[14];
tmp_14_reg_900[15] <= tmp_14_fu_779_p2[15];
tmp_14_reg_900[16] <= tmp_14_fu_779_p2[16];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2))) begin
        tmp_reg_851[2] <= tmp_fu_600_p3[2];
tmp_reg_851[3] <= tmp_fu_600_p3[3];
tmp_reg_851[4] <= tmp_fu_600_p3[4];
tmp_reg_851[5] <= tmp_fu_600_p3[5];
tmp_reg_851[6] <= tmp_fu_600_p3[6];
tmp_reg_851[7] <= tmp_fu_600_p3[7];
tmp_reg_851[8] <= tmp_fu_600_p3[8];
tmp_reg_851[9] <= tmp_fu_600_p3[9];
tmp_reg_851[10] <= tmp_fu_600_p3[10];
tmp_reg_851[11] <= tmp_fu_600_p3[11];
tmp_reg_851[12] <= tmp_fu_600_p3[12];
tmp_reg_851[13] <= tmp_fu_600_p3[13];
tmp_reg_851[14] <= tmp_fu_600_p3[14];
tmp_reg_851[15] <= tmp_fu_600_p3[15];
tmp_reg_851[16] <= tmp_fu_600_p3[16];
tmp_reg_851[17] <= tmp_fu_600_p3[17];
tmp_reg_851[18] <= tmp_fu_600_p3[18];
    end
end

/// ap_done assign process. ///
always @ (init_read_read_fu_110_p2 or exitcond1_reg_793 or ap_sig_cseq_ST_st10_fsm_9 or exitcond3_fu_684_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & (((init_read_read_fu_110_p2 == ap_const_lv1_0) & ~(exitcond1_reg_793 == ap_const_lv1_0)) | (~(init_read_read_fu_110_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == exitcond3_fu_684_p2))))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (init_read_read_fu_110_p2 or exitcond1_reg_793 or ap_sig_cseq_ST_st10_fsm_9 or exitcond3_fu_684_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & (((init_read_read_fu_110_p2 == ap_const_lv1_0) & ~(exitcond1_reg_793 == ap_const_lv1_0)) | (~(init_read_read_fu_110_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == exitcond3_fu_684_p2))))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st10_fsm_9 assign process. ///
always @ (ap_sig_bdd_209)
begin
    if (ap_sig_bdd_209) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st11_fsm_10 assign process. ///
always @ (ap_sig_bdd_227)
begin
    if (ap_sig_bdd_227) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_11 assign process. ///
always @ (ap_sig_bdd_135)
begin
    if (ap_sig_bdd_135) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st13_fsm_12 assign process. ///
always @ (ap_sig_bdd_349)
begin
    if (ap_sig_bdd_349) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st14_fsm_13 assign process. ///
always @ (ap_sig_bdd_247)
begin
    if (ap_sig_bdd_247) begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st15_fsm_14 assign process. ///
always @ (ap_sig_bdd_329)
begin
    if (ap_sig_bdd_329) begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_31)
begin
    if (ap_sig_bdd_31) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_150)
begin
    if (ap_sig_bdd_150) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_166)
begin
    if (ap_sig_bdd_166) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_128)
begin
    if (ap_sig_bdd_128) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st5_fsm_4 assign process. ///
always @ (ap_sig_bdd_342)
begin
    if (ap_sig_bdd_342) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_5 assign process. ///
always @ (ap_sig_bdd_186)
begin
    if (ap_sig_bdd_186) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_6 assign process. ///
always @ (ap_sig_bdd_300)
begin
    if (ap_sig_bdd_300) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st8_fsm_7 assign process. ///
always @ (ap_sig_bdd_195)
begin
    if (ap_sig_bdd_195) begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st9_fsm_8 assign process. ///
always @ (ap_sig_bdd_312)
begin
    if (ap_sig_bdd_312) begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    end
end

/// back_gauss_address0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_back_gauss_address0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12 or tmp_1_fu_608_p1 or tmp_20_fu_653_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        back_gauss_address0 = tmp_20_fu_653_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        back_gauss_address0 = tmp_1_fu_608_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        back_gauss_address0 = grp_backsub_EM_ALGO_fu_435_back_gauss_address0;
    end else begin
        back_gauss_address0 = 'bx;
    end
end

/// back_gauss_address1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_back_gauss_address1 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12 or tmp_17_fu_631_p1 or tmp_22_fu_675_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        back_gauss_address1 = tmp_22_fu_675_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        back_gauss_address1 = tmp_17_fu_631_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        back_gauss_address1 = grp_backsub_EM_ALGO_fu_435_back_gauss_address1;
    end else begin
        back_gauss_address1 = 'bx;
    end
end

/// back_gauss_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_back_gauss_ce0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        back_gauss_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        back_gauss_ce0 = grp_backsub_EM_ALGO_fu_435_back_gauss_ce0;
    end else begin
        back_gauss_ce0 = ap_const_logic_0;
    end
end

/// back_gauss_ce1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_back_gauss_ce1 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        back_gauss_ce1 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        back_gauss_ce1 = grp_backsub_EM_ALGO_fu_435_back_gauss_ce1;
    end else begin
        back_gauss_ce1 = ap_const_logic_0;
    end
end

/// back_gauss_d0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_back_gauss_d0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        back_gauss_d0 = ap_const_lv1_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        back_gauss_d0 = grp_backsub_EM_ALGO_fu_435_back_gauss_d0;
    end else begin
        back_gauss_d0 = 'bx;
    end
end

/// back_gauss_d1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_back_gauss_d1 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        back_gauss_d1 = ap_const_lv1_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        back_gauss_d1 = grp_backsub_EM_ALGO_fu_435_back_gauss_d1;
    end else begin
        back_gauss_d1 = 'bx;
    end
end

/// back_gauss_we0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or exitcond4_fu_588_p2 or grp_backsub_EM_ALGO_fu_435_back_gauss_we0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        back_gauss_we0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        back_gauss_we0 = grp_backsub_EM_ALGO_fu_435_back_gauss_we0;
    end else begin
        back_gauss_we0 = ap_const_logic_0;
    end
end

/// back_gauss_we1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or exitcond4_fu_588_p2 or grp_backsub_EM_ALGO_fu_435_back_gauss_we1 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        back_gauss_we1 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        back_gauss_we1 = grp_backsub_EM_ALGO_fu_435_back_gauss_we1;
    end else begin
        back_gauss_we1 = ap_const_logic_0;
    end
end

/// data_array_address0 assign process. ///
always @ (ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st11_fsm_10 or tmp_7_fu_556_p1 or tmp_6_fu_757_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        data_array_address0 = tmp_6_fu_757_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        data_array_address0 = tmp_7_fu_556_p1;
    end else begin
        data_array_address0 = 'bx;
    end
end

/// data_array_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st11_fsm_10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        data_array_ce0 = ap_const_logic_1;
    end else begin
        data_array_ce0 = ap_const_logic_0;
    end
end

/// grp_backsub_EM_ALGO_fu_435_pixel assign process. ///
always @ (reg_478 or pix_y1_reg_825 or pix_y1_1_reg_888 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        grp_backsub_EM_ALGO_fu_435_pixel = pix_y1_1_reg_888;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14))) begin
        grp_backsub_EM_ALGO_fu_435_pixel = reg_478;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        grp_backsub_EM_ALGO_fu_435_pixel = pix_y1_reg_825;
    end else begin
        grp_backsub_EM_ALGO_fu_435_pixel = 'bx;
    end
end

/// grp_backsub_EM_ALGO_fu_435_pos_r assign process. ///
always @ (tmp_8_reg_830 or tmp_12_reg_837 or tmp_5_reg_893 or tmp_14_reg_900 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        grp_backsub_EM_ALGO_fu_435_pos_r = tmp_14_reg_900;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        grp_backsub_EM_ALGO_fu_435_pos_r = tmp_5_reg_893;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        grp_backsub_EM_ALGO_fu_435_pos_r = tmp_12_reg_837;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        grp_backsub_EM_ALGO_fu_435_pos_r = tmp_8_reg_830;
    end else begin
        grp_backsub_EM_ALGO_fu_435_pos_r = 'bx;
    end
end

/// matchsum_address0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_matchsum_address0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12 or tmp_1_fu_608_p1 or tmp_20_fu_653_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        matchsum_address0 = tmp_20_fu_653_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        matchsum_address0 = tmp_1_fu_608_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        matchsum_address0 = grp_backsub_EM_ALGO_fu_435_matchsum_address0;
    end else begin
        matchsum_address0 = 'bx;
    end
end

/// matchsum_address1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or tmp_17_fu_631_p1 or tmp_22_fu_675_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        matchsum_address1 = tmp_22_fu_675_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        matchsum_address1 = tmp_17_fu_631_p1;
    end else begin
        matchsum_address1 = 'bx;
    end
end

/// matchsum_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_matchsum_ce0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        matchsum_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        matchsum_ce0 = grp_backsub_EM_ALGO_fu_435_matchsum_ce0;
    end else begin
        matchsum_ce0 = ap_const_logic_0;
    end
end

/// matchsum_ce1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        matchsum_ce1 = ap_const_logic_1;
    end else begin
        matchsum_ce1 = ap_const_logic_0;
    end
end

/// matchsum_d0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_matchsum_d0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        matchsum_d0 = ap_const_lv8_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        matchsum_d0 = grp_backsub_EM_ALGO_fu_435_matchsum_d0;
    end else begin
        matchsum_d0 = 'bx;
    end
end

/// matchsum_we0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or exitcond4_fu_588_p2 or grp_backsub_EM_ALGO_fu_435_matchsum_we0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        matchsum_we0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        matchsum_we0 = grp_backsub_EM_ALGO_fu_435_matchsum_we0;
    end else begin
        matchsum_we0 = ap_const_logic_0;
    end
end

/// matchsum_we1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or exitcond4_fu_588_p2 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        matchsum_we1 = ap_const_logic_1;
    end else begin
        matchsum_we1 = ap_const_logic_0;
    end
end

/// mean_address0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_mean_address0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12 or tmp_1_fu_608_p1 or tmp_20_fu_653_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        mean_address0 = tmp_20_fu_653_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        mean_address0 = tmp_1_fu_608_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        mean_address0 = grp_backsub_EM_ALGO_fu_435_mean_address0;
    end else begin
        mean_address0 = 'bx;
    end
end

/// mean_address1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or tmp_17_fu_631_p1 or tmp_22_fu_675_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        mean_address1 = tmp_22_fu_675_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        mean_address1 = tmp_17_fu_631_p1;
    end else begin
        mean_address1 = 'bx;
    end
end

/// mean_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_mean_ce0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        mean_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        mean_ce0 = grp_backsub_EM_ALGO_fu_435_mean_ce0;
    end else begin
        mean_ce0 = ap_const_logic_0;
    end
end

/// mean_ce1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        mean_ce1 = ap_const_logic_1;
    end else begin
        mean_ce1 = ap_const_logic_0;
    end
end

/// mean_d0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_mean_d0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        mean_d0 = ap_const_lv32_43340000;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        mean_d0 = ap_const_lv32_42000000;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        mean_d0 = grp_backsub_EM_ALGO_fu_435_mean_d0;
    end else begin
        mean_d0 = 'bx;
    end
end

/// mean_d1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        mean_d1 = ap_const_lv32_435C0000;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        mean_d1 = ap_const_lv32_42F00000;
    end else begin
        mean_d1 = 'bx;
    end
end

/// mean_we0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or exitcond4_fu_588_p2 or grp_backsub_EM_ALGO_fu_435_mean_we0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        mean_we0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        mean_we0 = grp_backsub_EM_ALGO_fu_435_mean_we0;
    end else begin
        mean_we0 = ap_const_logic_0;
    end
end

/// mean_we1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or exitcond4_fu_588_p2 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        mean_we1 = ap_const_logic_1;
    end else begin
        mean_we1 = ap_const_logic_0;
    end
end

/// out_frame_address0 assign process. ///
always @ (ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12 or tmp_s_fu_574_p1 or tmp_16_fu_584_p1 or tmp_10_fu_775_p1 or tmp_18_fu_785_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        out_frame_address0 = tmp_18_fu_785_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        out_frame_address0 = tmp_10_fu_775_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        out_frame_address0 = tmp_16_fu_584_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        out_frame_address0 = tmp_s_fu_574_p1;
    end else begin
        out_frame_address0 = 'bx;
    end
end

/// out_frame_ce0 assign process. ///
always @ (grp_backsub_EM_ALGO_fu_435_ap_done or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done)) | (~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done) & (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) | (~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done) & (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) | (~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done) & (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)))) begin
        out_frame_ce0 = ap_const_logic_1;
    end else begin
        out_frame_ce0 = ap_const_logic_0;
    end
end

/// out_frame_we0 assign process. ///
always @ (grp_backsub_EM_ALGO_fu_435_ap_done or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done)) | (~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done) & (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) | (~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done) & (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) | (~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done) & (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)))) begin
        out_frame_we0 = ap_const_logic_1;
    end else begin
        out_frame_we0 = ap_const_logic_0;
    end
end

/// sigma_address0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_sigma_address0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12 or tmp_1_fu_608_p1 or tmp_20_fu_653_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        sigma_address0 = tmp_20_fu_653_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        sigma_address0 = tmp_1_fu_608_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        sigma_address0 = grp_backsub_EM_ALGO_fu_435_sigma_address0;
    end else begin
        sigma_address0 = 'bx;
    end
end

/// sigma_address1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or tmp_17_fu_631_p1 or tmp_22_fu_675_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        sigma_address1 = tmp_22_fu_675_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        sigma_address1 = tmp_17_fu_631_p1;
    end else begin
        sigma_address1 = 'bx;
    end
end

/// sigma_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_sigma_ce0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        sigma_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        sigma_ce0 = grp_backsub_EM_ALGO_fu_435_sigma_ce0;
    end else begin
        sigma_ce0 = ap_const_logic_0;
    end
end

/// sigma_ce1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        sigma_ce1 = ap_const_logic_1;
    end else begin
        sigma_ce1 = ap_const_logic_0;
    end
end

/// sigma_d0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_sigma_d0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        sigma_d0 = ap_const_lv32_43C80000;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        sigma_d0 = grp_backsub_EM_ALGO_fu_435_sigma_d0;
    end else begin
        sigma_d0 = 'bx;
    end
end

/// sigma_we0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or exitcond4_fu_588_p2 or grp_backsub_EM_ALGO_fu_435_sigma_we0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        sigma_we0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        sigma_we0 = grp_backsub_EM_ALGO_fu_435_sigma_we0;
    end else begin
        sigma_we0 = ap_const_logic_0;
    end
end

/// sigma_we1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or exitcond4_fu_588_p2 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        sigma_we1 = ap_const_logic_1;
    end else begin
        sigma_we1 = ap_const_logic_0;
    end
end

/// weight_address0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_weight_address0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12 or tmp_1_fu_608_p1 or tmp_20_fu_653_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        weight_address0 = tmp_20_fu_653_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        weight_address0 = tmp_1_fu_608_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        weight_address0 = grp_backsub_EM_ALGO_fu_435_weight_address0;
    end else begin
        weight_address0 = 'bx;
    end
end

/// weight_address1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or tmp_17_fu_631_p1 or tmp_22_fu_675_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        weight_address1 = tmp_22_fu_675_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        weight_address1 = tmp_17_fu_631_p1;
    end else begin
        weight_address1 = 'bx;
    end
end

/// weight_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_weight_ce0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        weight_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        weight_ce0 = grp_backsub_EM_ALGO_fu_435_weight_ce0;
    end else begin
        weight_ce0 = ap_const_logic_0;
    end
end

/// weight_ce1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        weight_ce1 = ap_const_logic_1;
    end else begin
        weight_ce1 = ap_const_logic_0;
    end
end

/// weight_d0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or grp_backsub_EM_ALGO_fu_435_weight_d0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        weight_d0 = ap_const_lv32_3D4CCCCD;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        weight_d0 = grp_backsub_EM_ALGO_fu_435_weight_d0;
    end else begin
        weight_d0 = 'bx;
    end
end

/// weight_we0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or exitcond4_fu_588_p2 or grp_backsub_EM_ALGO_fu_435_weight_we0 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        weight_we0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        weight_we0 = grp_backsub_EM_ALGO_fu_435_weight_we0;
    end else begin
        weight_we0 = ap_const_logic_0;
    end
end

/// weight_we1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or exitcond4_fu_588_p2 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond4_fu_588_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        weight_we1 = ap_const_logic_1;
    end else begin
        weight_we1 = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or init_read_read_fu_110_p2 or exitcond1_fu_483_p2 or exitcond1_reg_793 or exitcond_fu_539_p2 or exitcond4_fu_588_p2 or exitcond3_fu_684_p2 or exitcond2_fu_740_p2 or grp_backsub_EM_ALGO_fu_435_ap_done)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if ((~(ap_start == ap_const_logic_0) & ~(init_read_read_fu_110_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else if ((~(ap_start == ap_const_logic_0) & (init_read_read_fu_110_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((exitcond1_fu_483_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if ((ap_const_lv1_0 == exitcond_fu_539_p2)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            if (~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            if (~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st8_fsm_7 : 
        begin
            if (~(ap_const_lv1_0 == exitcond4_fu_588_p2)) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        end
        ap_ST_st9_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st10_fsm_9 : 
        begin
            if ((((init_read_read_fu_110_p2 == ap_const_lv1_0) & ~(exitcond1_reg_793 == ap_const_lv1_0)) | (~(init_read_read_fu_110_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == exitcond3_fu_684_p2)))) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        end
        ap_ST_st11_fsm_10 : 
        begin
            if ((ap_const_lv1_0 == exitcond2_fu_740_p2)) begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : 
        begin
            if (~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done)) begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end else begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end
        end
        ap_ST_st14_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st15_fsm_14 : 
        begin
            if (~(ap_const_logic_0 == grp_backsub_EM_ALGO_fu_435_ap_done)) begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_return = ap_const_lv32_0;

/// ap_sig_bdd_128 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_128 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_135 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_135 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end

/// ap_sig_bdd_150 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_150 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_166 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_166 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_186 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_186 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_195 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_195 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end

/// ap_sig_bdd_209 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_209 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end

/// ap_sig_bdd_227 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_227 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end

/// ap_sig_bdd_247 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_247 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_D]);
end

/// ap_sig_bdd_300 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_300 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_31 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_31 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_312 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_312 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end

/// ap_sig_bdd_329 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_329 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end

/// ap_sig_bdd_342 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_342 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_349 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_349 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end
assign exitcond1_fu_483_p2 = (idxRow2_reg_379 == ap_const_lv8_F0? 1'b1: 1'b0);
assign exitcond2_fu_740_p2 = (idxCols_reg_423 == ap_const_lv8_A0? 1'b1: 1'b0);
assign exitcond3_fu_684_p2 = (idxRow_reg_412 == ap_const_lv8_F0? 1'b1: 1'b0);
assign exitcond4_fu_588_p2 = (i_reg_401 == ap_const_lv17_12C00? 1'b1: 1'b0);
assign exitcond_fu_539_p2 = (idxCols3_reg_390 == ap_const_lv8_A0? 1'b1: 1'b0);
assign grp_backsub_EM_ALGO_fu_435_ap_start = grp_backsub_EM_ALGO_fu_435_ap_start_ap_start_reg;
assign grp_backsub_EM_ALGO_fu_435_back_gauss_q0 = back_gauss_q0;
assign grp_backsub_EM_ALGO_fu_435_matchsum_q0 = matchsum_q0;
assign grp_backsub_EM_ALGO_fu_435_mean_q0 = mean_q0;
assign grp_backsub_EM_ALGO_fu_435_sigma_q0 = sigma_q0;
assign grp_backsub_EM_ALGO_fu_435_weight_q0 = weight_q0;
assign i_1_fu_594_p2 = (i_reg_401 + ap_const_lv17_1);
assign i_2_fu_551_p2 = (idxCols3_cast2_fu_535_p1 + p_lshr_f1_cast_reg_802);
assign i_3_fu_752_p2 = (idxCols_cast6_fu_736_p1 + p_lshr_f_cast_reg_865);
assign idxCols3_cast2_fu_535_p1 = idxCols3_reg_390;
assign idxCols_1_fu_545_p2 = (idxCols3_reg_390 + ap_const_lv8_1);
assign idxCols_2_fu_746_p2 = (idxCols_reg_423 + ap_const_lv8_1);
assign idxCols_cast6_fu_736_p1 = idxCols_reg_423;
assign idxRow_1_fu_489_p2 = (idxRow2_reg_379 + ap_const_lv8_1);
assign idxRow_2_fu_690_p2 = (idxRow_reg_412 + ap_const_lv8_1);
assign init_read_read_fu_110_p2 = init;
assign matchsum_d1 = ap_const_lv8_0;
assign mean_addr1_fu_623_p3 = {{ap_const_lv13_0}, {tmp_11_fu_617_p2}};
assign mean_addr2_fu_645_p3 = {{ap_const_lv13_0}, {tmp_19_fu_640_p2}};
assign mean_addr3_fu_667_p3 = {{ap_const_lv13_0}, {tmp_21_fu_662_p2}};
assign out_frame_d0 = ((grp_backsub_EM_ALGO_fu_435_ap_return)? ap_const_lv8_FF: ap_const_lv8_0);
assign p_shl1_cast_fu_503_p1 = p_shl1_fu_495_p3;
assign p_shl1_fu_495_p3 = {{idxRow2_reg_379}, {ap_const_lv8_0}};
assign p_shl2_cast_fu_515_p1 = p_shl2_fu_507_p3;
assign p_shl2_fu_507_p3 = {{idxRow2_reg_379}, {ap_const_lv6_0}};
assign p_shl3_cast_fu_716_p1 = p_shl3_fu_708_p3;
assign p_shl3_fu_708_p3 = {{idxRow_reg_412}, {ap_const_lv6_0}};
assign p_shl_cast_fu_704_p1 = p_shl_fu_696_p3;
assign p_shl_fu_696_p3 = {{idxRow_reg_412}, {ap_const_lv8_0}};
assign pix_y1_1_fu_762_p1 = data_array_q0[7:0];
assign pix_y1_fu_561_p1 = data_array_q0[7:0];
assign sigma_d1 = ap_const_lv32_43C80000;
assign tmp_10_fu_775_p1 = tmp_5_reg_893;
assign tmp_11_fu_617_p2 = (tmp_fu_600_p3 | ap_const_lv19_1);
assign tmp_12_fu_578_p2 = (tmp_8_reg_830 | ap_const_lv17_1);
assign tmp_14_fu_779_p2 = (tmp_5_reg_893 | ap_const_lv17_1);
assign tmp_16_fu_584_p1 = tmp_12_reg_837;
assign tmp_17_fu_631_p1 = mean_addr1_fu_623_p3;
assign tmp_18_fu_785_p1 = tmp_14_reg_900;
assign tmp_19_fu_640_p2 = (tmp_reg_851 | ap_const_lv19_2);
assign tmp_1_fu_608_p1 = tmp_fu_600_p3;
assign tmp_20_fu_653_p1 = mean_addr2_fu_645_p3;
assign tmp_21_fu_662_p2 = (tmp_reg_851 | ap_const_lv19_3);
assign tmp_22_fu_675_p1 = mean_addr3_fu_667_p3;
assign tmp_2_fu_519_p2 = (p_shl1_cast_fu_503_p1 + p_shl2_cast_fu_515_p1);
assign tmp_4_fu_720_p2 = (p_shl_cast_fu_704_p1 + p_shl3_cast_fu_716_p1);
assign tmp_5_fu_767_p3 = {{i_3_reg_878}, {ap_const_lv1_0}};
assign tmp_6_fu_757_p1 = i_3_fu_752_p2;
assign tmp_7_fu_556_p1 = i_2_fu_551_p2;
assign tmp_8_fu_566_p3 = {{i_2_reg_815}, {ap_const_lv1_0}};
assign tmp_fu_600_p3 = {{i_reg_401}, {ap_const_lv2_0}};
assign tmp_s_fu_574_p1 = tmp_8_reg_830;
assign weight_d1 = ap_const_lv32_3D4CCCCD;
always @ (posedge ap_clk)
begin
    tmp_8_reg_830[0] <= 1'b0;
    tmp_12_reg_837[0] <= 1'b1;
    tmp_reg_851[1:0] <= 2'b00;
    tmp_5_reg_893[0] <= 1'b0;
    tmp_14_reg_900[0] <= 1'b1;
end



endmodule //backsub

